---
name: Docker
on:
  - push
  - pull_request
jobs:
  docker-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docker
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag $GITHUB_REPOSITORY:$(date +%s)
